/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skyinu_vm_eraser_VMEraser */

#ifndef _Included_com_skyinu_vm_eraser_VMEraser
#define _Included_com_skyinu_vm_eraser_VMEraser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_skyinu_vm_eraser_VMEraser
 * Method:    eraser
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_skyinu_vm_1eraser_VMEraser_eraser
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
